---
title: "Supplemental Figure 4"
output: rmarkdown::github_document
---


## Setup

Load R libraries
```{r message=FALSE, load_r_libraries}
library(tidyverse)
library(glue)
library(rlang)
library(parameters)
library(ggforestplot)
library(rmarkdown)
library(knitr)
library(scattermore)
library(magrittr)
library(alakazam)
library(ggrepel)
library(ggpubr)

library(reticulate)
use_python("/projects/home/nealpsmith/.conda/envs/updated_pegasus/bin/python")

setwd('../../functions')

source('stacked_bar.R')
source('blood_condition_abundance.R')
source('blood_fatal_abundance.R')
source('tcr_functions.R')

```

Load Python packages
```{python load_python_packages}
import pegasus as pg
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append("/projects/home/ikernin/github_code/myocarditis/functions")
import python_functions
```

Read in single-cell data

```{python results='hide', read_data}
blood_cd8_nk = pg.read_input('/projects/home/ikernin/projects/myocarditis/github_datasets/blood_cd8.zarr')
tissue_t = pg.read_input('/projects/home/ikernin/projects/myocarditis/github_datasets/tissue_t.zarr')
```

Read in TCR data

```{r read_tcr}
# Blood TCR info
bulk_tcr_df <- read.csv("/projects/home/nealpsmith/projects/myocarditis/data/adaptive/all_productive_tcrs.csv",
                        row.names = 1)

blood_sc_info = read.csv("/projects/home/nealpsmith/projects/myocarditis/tissue/data/tcr/blood_tissue_comps/cell_info.csv",
                     row.names = 1)
tissue_sc_info <- read.csv("/projects/home/nealpsmith/projects/myocarditis/tissue/data/tcr/blood_tissue_comps/tissue_cell_info.csv",
                             row.names = 1)
tissue_sc_info <- tissue_sc_info[tissue_sc_info$TRB_cdr3 != "",]



bulk_tissue_samples = list("SIC_3" = list("tumor" = "A17-341_A2", "control" = "A17-341_A3", "myo" = "A17-341_A27"),
                           "SIC_232" = list("tumor" = "A19-395_A8", "control" = "A19-395_A7", "myo" = "A19-395_A53-1"),
                           "SIC_136" = list("tumor" = "A19-41_A10_Tumor", "control" = "A19-41_A10_Liver", "myo" = "A19-41_A33"),
                           "SIC_17" = list("tumor" = "A18-122_A51", "control" = "A18-122_A52", "myo" = "A18-122_A41"),
                           "SIC_175" = list("tumor" = "A19-230_A5", "control" = "T03054-11", "myo" = "A19-230_A48"),
                           "SIC_266" = list("myo" = "A20-363_A18"),
                           "SIC_264" = list("myo" = "A20-331_A1"),
                           # These are controls
                           "SIC_176" = list("myo" = "A19-213_A13"),
                           "SIC_14" = list("myo" = "T01708-11"),
                           "SIC_182" = list("myo" = "A19-240_A15"),
                           "T01241" = list("myo" = "A16-303_A5")
)

```

## Supplemental Figure 4A

```{python results='hold', supp_4a}
# plot gene featureplots
supp_fig4a_genes = ['CD3D', 'CD8A', 'FCER1G', 'CD28']
python_functions.multi_hex_featureplot(blood_cd8_nk,
                      supp_fig4a_genes,
                      ncol=2,
                      cmap=python_functions.blues_cmap,
                      gridsize=200)

# plot percent_mito and n_genes
python_functions.hex_plot(blood_cd8_nk, '% Mito', n_genes=False, gridsize=200, cmap=python_functions.blues_cmap)
python_functions.hex_plot(blood_cd8_nk, 'N Genes', n_genes=True, gridsize=200, cmap=python_functions.blues_cmap)
```


## Supplemental Figure 4B

```{r message = F, results = 'hold', supp_4b}
# read in all blood cell metadata
blood_global_obs <- read_csv('/projects/home/ikernin/projects/myocarditis/github_datasets/blood_global_obs.csv')
condition_blood_obs_filtered <- condition_filter_df(blood_global_obs)

# fit cluster level model
condition_cluster_percents <- condition_get_percent_per_level(condition_blood_obs_filtered, level='cluster')
condition_cluster_model <- condition_fit_model(condition_cluster_percents, level='cluster')
condition_cluster_lineages <- condition_blood_obs_filtered %>% select(cluster_names, lineage_names) %>% distinct()

# get get cd8 lineage level results
cd8_order <- c('b-CD8T: ZNF683 GNLY',
               'b-CD8T: CX3CR1 IKZF2',
               'b-CD8T: TCF7 ITGb',
               'b-CD8T: HLA-DRA RGS1',
               'b-CD8T: IL7R GZMK',
               'b-CD8T: cycling',
               'b-CD8T: CCL3 IFNG',
               'b-CD8T/NK: MT-high',
               'b-MAIT: TRAV1-2 KLRb',
               "b-NK: SPON2 FCER1G",
               'b-NK: KIR2DL3 KLRC2',
               'b-NK: SPTSSB XCL1'
        )
condition_cd8_percents <- condition_cluster_percents %>% filter(cluster_names %in% cd8_order)
condition_cd8_percents <- set_factor_order(condition_cd8_percents , col_name = 'cluster_names', order = cd8_order)
condition_cd8_model <- condition_cluster_model %>% filter(cluster_names %in% cd8_order)
condition_cd8_model <- set_factor_order(condition_cd8_model , col_name = 'cluster_names', order = cd8_order)
kable(condition_cd8_model %>%
              select(!c(data, model)) %>%
              unnest(cols = c(condition_coef, condition_se, condition_pval)))

condition_plot_sample_perc(condition_cd8_percents, title='CD4')
condition_plot_ci_interval(condition_cd8_model, 'CD4', level='cluster')
```


## Supplemental Figure 4C

```{r message = F, results = 'hold', supp_4c}
# read in all blood cell metadata
fatal_blood_obs_filtered <- fatal_filter_df(blood_global_obs)

# fit cluster level model
fatal_cluster_percents <- fatal_get_percent_per_level(fatal_blood_obs_filtered, level='cluster')
fatal_cluster_model <- fatal_fit_model(fatal_cluster_percents, level='cluster')
fatal_cluster_lineages <- fatal_blood_obs_filtered %>% select(cluster_names, lineage_names) %>% distinct()

# get get cd8 lineage level results
fatal_cd8_percents <- fatal_cluster_percents %>% filter(cluster_names %in% cd8_order)
fatal_cd8_percents <- set_factor_order(fatal_cd8_percents , col_name = 'cluster_names', order = cd8_order)
fatal_cd8_model <- fatal_cluster_model %>% filter(cluster_names %in% cd8_order)
fatal_cd8_model <- set_factor_order(fatal_cd8_model , col_name = 'cluster_names', order = cd8_order)
kable(fatal_cd8_model %>%
              select(!c(data, model)) %>%
              unnest(cols = c(fatal_coef, fatal_se, fatal_pval)))

fatal_plot_sample_perc(fatal_cd8_percents, title='CD4')
fatal_plot_ci_interval(fatal_cd8_model, 'CD4', level='cluster')

```

## Figure S4D

```{r fig_s4d, message=FALSE, warning=FALSE, fig.height = 10, fig.width = 8}

n_uniques <- blood_sc_info %>%
  dplyr::select(TRB_cdr3, donor, timepoint_cat) %>%
  dplyr::filter(TRB_cdr3 != "", timepoint_cat %in% c("on_ici", "pre_steroid")) %>%
  distinct() %>%
  group_by(donor, timepoint_cat) %>%
  summarise(n = n()) %>%
  mutate(dtype ="unique~TCR*beta")

# Now the total number
n_total <- blood_sc_info %>%
  dplyr::select(TRB_cdr3, donor, timepoint_cat) %>%
  dplyr::filter(TRB_cdr3 != "", timepoint_cat %in% c("on_ici", "pre_steroid")) %>%
  group_by(donor, timepoint_cat) %>%
  summarise(n = n()) %>%
  mutate(dtype = "total~TCR*beta")

plot_df <- rbind(n_total, n_uniques)
plot_df$dtype <- factor(plot_df$dtype, levels = c("unique~TCR*beta", "total~TCR*beta"))
# plot_df$timepoint_cat <- sapply(plot_df$timepoint_cat, function(x) sub("_", " ", x))
plot_df$timepoint_cat <- as.character(plot_df$timepoint_cat)

ggplot(plot_df, aes(x = n, y = donor)) +
  geom_bar(stat = "identity") +
  scale_x_log10() +
  annotation_logticks(side = "b", outside = TRUE) +
  coord_cartesian(clip = "off") +
  xlab("# sequences") +
  facet_grid(timepoint_cat~dtype, labeller = label_parsed, scales = "free_y", space = "free_y") +
  theme_classic(base_size = 20)

```

## Supplemental figure 4E

```{r fig_S4E, message = FALSE, warning = FALSE}

blood_overlap_subjs <- intersect(c(names(bulk_tissue_samples), unique(tissue_sc_info$donor)), unique(blood_sc_info$donor))

# Don't include bulk healing
healing_ids <- c("SIC_3", "SIC_175", "SIC_266", "SIC_232")

myo_exp_tcrs <- lapply(blood_overlap_subjs, function(s){
  subj_tcrs <- c()
  # See if they have bulk TCR
  if(s %in% names(bulk_tissue_samples)){
    if (!s %in% healing_ids){
      bulk_samp <- bulk_tissue_samples[[s]]$myo
      bulk_tcrs <- bulk_tcr_df[bulk_tcr_df$sample == bulk_samp,] %>%
        dplyr::select(amino_acid, count_templates_reads) %>%
        group_by(amino_acid) %>%
        summarise(n = sum(count_templates_reads)) %>%
        mutate(perc = n / sum(n) * 100)
    bulk_exp <- bulk_tcrs$amino_acid[bulk_tcrs$perc > 0.5 & bulk_tcrs$n > 1]
    subj_tcrs <- c(subj_tcrs, bulk_exp)
    }

  }
  # See if they have single cell TCR
  if (s %in% unique(tissue_sc_info$donor)){
    subj_sc <- tissue_sc_info[tissue_sc_info$donor == s,] %>%
      dplyr::filter(TRB_cdr3 != "") %>%
      dplyr::select(TRB_cdr3) %>%
      mutate("count" =  1) %>%
      group_by(TRB_cdr3) %>%
      summarise(n = sum(count)) %>%
      mutate(perc = n / sum(n) * 100)
    sc_exp <- subj_sc$TRB_cdr3[subj_sc$perc > 0.5 & subj_sc$n > 1]
    subj_tcrs <- c(subj_tcrs, sc_exp)
  }
  return(unique(subj_tcrs))
})
names(myo_exp_tcrs) <- blood_overlap_subjs


# Now one for overall
plot_df <- blood_sc_info
plot_df$myo_clone <- FALSE
for (s in blood_overlap_subjs){
  myo_clones <- myo_exp_tcrs[[s]]
  plot_df$myo_clone[plot_df$donor == s & plot_df$TRB_cdr3 %in% myo_clones] <- TRUE

}

ggplot(plot_df, aes(x = umap_1, y = umap_2)) +
  geom_scattermore(data = plot_df[plot_df$myo_clone == FALSE,], color = "grey", size = 1) +
  geom_point(data = plot_df[plot_df$myo_clone == TRUE,], color = "red", size = 2) +
  xlab("UMAP1") + ylab("UMAP2") +
  theme_classic(base_size = 20) +
  theme(axis.ticks = element_blank(), axis.text = element_blank())
```


## Supplemental Figure 4F

```{r fig_S4F, message = FALSE, warning = FALSE}

blood_overlap_subjs <- intersect(c(names(bulk_tissue_samples), unique(tissue_sc_info$donor)), unique(blood_sc_info$donor))
# Need to remove healing myocarditis (for which we have bulk TCR for), its different
healing_ids <- c("SIC_3", "SIC_175", "SIC_266")

myo_exp_tcrs <- lapply(blood_overlap_subjs, function(s){
  subj_tcrs <- c()
  # See if they have bulk TCR
  if(s %in% names(bulk_tissue_samples)){
    if (!s %in% healing_ids){
      bulk_samp <- bulk_tissue_samples[[s]]$myo
      bulk_tcrs <- bulk_tcr_df[bulk_tcr_df$sample == bulk_samp,] %>%
        dplyr::select(amino_acid, count_templates_reads) %>%
        group_by(amino_acid) %>%
        summarise(n = sum(count_templates_reads)) %>%
        mutate(perc = n / sum(n) * 100)
    bulk_exp <- bulk_tcrs$amino_acid[bulk_tcrs$perc > 0.5 & bulk_tcrs$n > 1]
    subj_tcrs <- c(subj_tcrs, bulk_exp)
    }

  }
  # See if they have single cell TCR
  if (s %in% unique(tissue_sc_info$donor)){
    subj_sc <- tissue_sc_info[tissue_sc_info$donor == s,] %>%
      dplyr::filter(TRB_cdr3 != "") %>%
      dplyr::select(TRB_cdr3) %>%
      mutate("count" =  1) %>%
      group_by(TRB_cdr3) %>%
      summarise(n = sum(count)) %>%
      mutate(perc = n / sum(n) * 100)
    sc_exp <- subj_sc$TRB_cdr3[subj_sc$perc > 0.5 & subj_sc$n > 1]
    subj_tcrs <- c(subj_tcrs, sc_exp)
  }
  return(unique(subj_tcrs))
})
names(myo_exp_tcrs) <- blood_overlap_subjs

info_df <- blood_sc_info[blood_sc_info$donor %in% blood_overlap_subjs,]
info_df$myo_clone <- "False"
for (s in blood_overlap_subjs){
  myo_clones <- myo_exp_tcrs[[s]]
  info_df$myo_clone[info_df$donor == s & info_df$TRB_cdr3 %in% myo_clones] <- "True"
}

df <- tcr_assoc_func(info_df, cluster = info_df$leiden_labels, contrast = "myo_clone")

new_names <- c("cluster1" = "2. b-NK",
               "cluster2" = "1. b-CD8T",
               "cluster3" = "3. b-CD8T",
               "cluster4" = "4. b-CD8T",
               "cluster5" = "5. b-NK",
               "cluster6" = "6. b-CD8T",
               "cluster7" = "7. b-CD8T",
               "cluster8" = "8. b-CD8T/NK",
               "cluster9" = "MNP/T doublets",
               "cluster10" = "9. b-MAIT",
               "cluster11" = "10.b-NK",
               "cluster12" = "11. b-CD8T",
               "cluster13" = "12. b-CD8T")
df$cluster <- sapply(df$cluster, function(x) new_names[[x]])


ggplot(df, aes(x = myo_clone.OR, y = -log10(model.pvalue))) +
  geom_errorbarh(data = df[df$model.padj < 0.05 & df$myo_clone.OR > 1.42,],
                 aes(xmax = myo_clone.OR.95pct.ci.upper, xmin = myo_clone.OR.95pct.ci.lower),
                 color = "grey", height = 0) +
  geom_point(data = df[df$model.padj > 0.05 | df$myo_clone.OR < 1.42,],
             color = "grey") +
  geom_point(data = df[df$model.padj < 0.05 & df$myo_clone.OR > 1.42,],
             color = "red", size = 3) +
  geom_text_repel(data = df[df$model.padj < 0.05 & df$myo_clone.OR > 1.42,],
                  aes(label = cluster), size = 5, direction = "y") +
  geom_vline(xintercept = 1, linetype = "dashed") +
  xlab("OR") + ylab("-log10(p-value)") +
  theme_classic(base_size = 20)

```


## Supplemental Figure 4G

```{r fig_S4G, message = FALSE, warning = FALSE}

# Only take cells with full TCR info
cd8_info <- blood_sc_info[blood_sc_info$TRA_cdr3 != "" & blood_sc_info$TRB_cdr3 != "" &
                             blood_sc_info$TRA_v_gene != "" & blood_sc_info$TRB_v_gene != "",]

# Change the column name to be compatible
colnames(cd8_info)[colnames(cd8_info) == "clone"] <- "clone_id"

div_df <- cd8_info[,c("clone_id", "sample_id")]

div <- alphaDiversity(div_df, group = "sample_id", nboot = 100, min_n = 100)

# Add timepoint info
timepoint_info <- cd8_info %>%
  dplyr::select("sample_id", "timepoint_cat", "donor") %>%
  distinct()

div %<>%
  left_join(timepoint_info, by = "sample_id")
div$timepoint_cat <- factor(div$timepoint_cat)
div$donor <- factor(div$donor)

plot_df <- div[div$timepoint_cat %in% c("on_ici", "pre_steroid"),]

ggplot(plot_df, aes_string(x = "q", y = "d", group = "sample_id", color = "timepoint_cat")) +
  geom_line() +
  # facet_wrap(~donor) +
  scale_color_manual(values = c("blue", "red")) +
  ggtitle("Hill diversity index") + baseTheme() +
  xlab("q") + ylab("d") +
  theme_classic(base_size = 20) +
  theme(legend.title = element_blank())

```

## Supplemental Figure 4H

```{r supp_4H, warning = FALSE, message = FALSE, fig.width = 12, fig.height = 12}

subj_order <- c("SIC_232", "SIC_17", "SIC_175", "SIC_264", "SIC_136", "SIC_258", "SIC_48", "SIC_197",
                "SIC_177", "SIC_164", "SIC_217", "SIC_153", "SIC_171")

plot_list <- list()
for (s in subj_order){
  myo_clones <- myo_exp_tcrs[[s]]

  plot_df <- blood_sc_info
  plot_df$myo_clone <- ifelse(plot_df$donor == s & plot_df$TRB_cdr3 %in% myo_clones, TRUE, FALSE)

  plot <- ggplot(plot_df, aes(x = umap_1, y = umap_2)) +
    geom_scattermore(data = plot_df[plot_df$myo_clone == FALSE,], color = "grey", size = 1) +
    geom_point(data = plot_df[plot_df$myo_clone == TRUE,], color = "red", size = 2) +
    xlab("") + ylab("") +
    theme_classic(base_size = 20) +
    ggtitle(s) +
    theme(axis.ticks = element_blank(), axis.text = element_blank())
  plot_list <- c(plot_list, list(plot))

}
figure <- ggarrange(plotlist = plot_list, ncol = 4, nrow = 4, common.legend = TRUE, legend = "right")
figure

```

## Supplemental Figure 4I

```{r supp_4I, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 8}

# This dataframe is the same as "tissue_sc_info",
# but includes all cells (not just those tissue cells with a recovered TCR)
tissue_cell_info <- read.csv("/projects/home/nealpsmith/projects/myocarditis/tissue/data/tcr/blood_tissue_comps/tissue_cell_info.csv",
                             row.names = 1)


# Make the associated UMAPs
subj_list <- tissue_cell_info %>%
  dplyr::filter(blood_clone == "True") %>%
  dplyr::select(donor, blood_clone) %>%
  group_by(donor) %>%
  summarise(n=n()) %>%
  dplyr::filter(n > 10) %>%
  .$donor

plot_list <- list()
for (s in subj_list){
  plot_df <- tissue_cell_info
  plot_df$blood_clone <- ifelse(plot_df$donor == s & plot_df$blood_clone == "True", "TRUE", "FALSE")

  plot <- ggplot(plot_df, aes(x = umap_1, y = umap_2)) +
    geom_point(data = plot_df[plot_df$blood_clone == "FALSE",], aes(fill = blood_clone), color = "grey", size = 1) +
    geom_point(data = plot_df[plot_df$blood_clone == "TRUE",], pch = 21, aes(fill = blood_clone), size = 1.5) +
    xlab("") + ylab("") +
    scale_fill_manual(name = "Blood TCR", breaks = c("TRUE", "FALSE"),
                      values = c("TRUE" = "red", "FALSE" = "grey")) +
    theme_classic(base_size = 20) +
    ggtitle(s) +
    theme(axis.ticks = element_blank(), axis.text = element_blank())
  plot_list <- c(plot_list, list(plot))

}
all_plots <- ggarrange(plotlist = plot_list, common.legend = TRUE)
all_plots

```

## Supplemental Figure 4J

```{python supp_4j}

supp_fig4j_genes = ['CXCR3', 'CX3CR1']
python_functions.multi_hex_featureplot(tissue_t,
                      supp_fig4j_genes,
                      ncol=2,
                      cmap=python_functions.blues_cmap,
                      gridsize=200)

```












