---
title: "Supplemental Figure 4"
output: rmarkdown::github_document
---

## Setup

Load R libraries
```{r message=FALSE, load_r_libraries}
library(tidyverse)
library(glue)
library(ggpubr)
library(ggplot2)
library(magrittr)
library(ggrepel)

```

Read in the TCR data
```{r tcr_info}
bulk_tcr_df <- read.csv("/projects/home/nealpsmith/projects/myocarditis/data/adaptive/all_productive_tcrs.csv",
                        row.names = 1)
blood_sc_info = read.csv("/projects/home/nealpsmith/projects/myocarditis/tissue/data/tcr/blood_tissue_comps/cell_info.csv",
                     row.names = 1)
tissue_sc_info <- read.csv("/projects/home/nealpsmith/projects/myocarditis/tissue/data/tcr/blood_tissue_comps/tissue_cell_info.csv",
                             row.names = 1)
tissue_sc_info <- tissue_sc_info[tissue_sc_info$TRB_cdr3 != "",]
### Okay lets look at the overlap between tumor and myocarditis and tumor control in our subjects ###
bulk_tissue_samples = list("SIC_3" = list("tumor" = "A17-341_A2", "control" = "A17-341_A3", "myo" = "A17-341_A27"),
                           "SIC_232" = list("tumor" = "A19-395_A8", "control" = "A19-395_A7", "myo" = "A19-395_A53-1"),
                           "SIC_136" = list("tumor" = "A19-41_A10_Tumor", "control" = "A19-41_A10_Liver", "myo" = "A19-41_A33"),
                           "SIC_17" = list("tumor" = "A18-122_A51", "control" = "A18-122_A52", "myo" = "A18-122_A41"),
                           "SIC_175" = list("tumor" = "A19-230_A5", "control" = "T03054-11", "myo" = "A19-230_A48"),
                           "SIC_266" = list("myo" = "A20-363_A18"),
                           "SIC_264" = list("myo" = "A20-331_A1"),
                           # These are controls
                           "SIC_176" = list("myo" = "A19-213_A13"),
                           "SIC_14" = list("myo" = "T01708-11"),
                           # "SIC_182" = list("myo" = "A19-240_A15"),
                           "T01241" = list("myo" = "A16-303_A5")
)


```

## Supplemental figure 4A

```{r fig_S4A, message=FALSE, warning=FALSE}

plot_df <- read.csv("/projects/home/nealpsmith/projects/myocarditis/data/adaptive/perc_tcrb_of_nucleated_cells.csv")
plot_df$perc <- plot_df$perc * 100
plot_df$category[plot_df$category == "case"] <- "irMyocarditis"

ggplot(plot_df, aes(x = category, y = perc, fill = category)) +
  geom_boxplot(alpha = 0.8) +
  geom_jitter(width = 0.3, pch = 21, size = 4) +
  scale_fill_manual(values = c("#6f8090", "#8a3624")) +
  scale_y_log10() +
  annotation_logticks(side = "l", outside = TRUE) +
  coord_cartesian(clip = "off") +
  xlab("") +
  ylab("% TCRB retreival of nucleated cells") +
  theme_classic(base_size = 15) +
  theme(legend.position = "none")

```


## Supplemental figure 4B

```{r fig_s4b, message=FALSE, warning=FALSE, fig.width=10, fig.height = 8}
blood_overlap_subjs <- intersect(c(names(bulk_tissue_samples), unique(tissue_sc_info$donor)), unique(blood_sc_info$donor))

# Need to remove SIC_3, its healing myocarditis, so different
blood_overlap_subjs <- blood_overlap_subjs[blood_overlap_subjs != "SIC_3"]

# Don't include bulk healing
healing_ids <- c("SIC_3", "SIC_175", "SIC_266", "SIC_232")

myo_tcrs <- lapply(blood_overlap_subjs, function(s){
  subj_tcrs <- c()
  # See if they have bulk TCR
  if(s %in% names(bulk_tissue_samples)){
    if (!s %in% healing_ids){
      bulk_samp <- bulk_tissue_samples[[s]]$myo
      bulk_tcrs <- unique(bulk_tcr_df$amino_acid[bulk_tcr_df$sample == bulk_samp])
      subj_tcrs <- c(subj_tcrs, bulk_tcrs)
    }
  }
  # See if they have single cell TCR
  if (s %in% unique(tissue_sc_info$donor)){
    subj_sc <- tissue_sc_info[tissue_sc_info$donor == s,] %>%
      dplyr::filter(TRB_cdr3 != "")
    sc_tcrs <- unique(subj_sc$TRB_cdr3)
    subj_tcrs <- c(subj_tcrs, sc_tcrs)
  }
  return(subj_tcrs)
})
names(myo_tcrs) <- blood_overlap_subjs


n_tcrs <- lapply(myo_tcrs, function(x) length(x)) %>%
  as.data.frame() %>%
  t() %>%
  `colnames<-`(c("n")) %>%
  as.data.frame() %>%
  rownames_to_column(var = "subj")

bars <- ggplot(n_tcrs, aes(x = n, y = subj)) +
  geom_bar(stat = "identity") +
  scale_x_log10(breaks = c(1, 10, 100, 1000)) +
  annotation_logticks(side = "b", outside = TRUE) +
  coord_cartesian(clip = "off") +
  ylab("") +
  xlab("# unique CDR3s") +
  theme_classic(base_size = 20) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")

# Which datasets did each subject have?
dset_df <- data.frame()
for (s in blood_overlap_subjs){
  if (!s %in% healing_ids){
    bulk <- s %in% names(bulk_tissue_samples)
  } else {
    bulk <- FALSE
  }
  sc <- s %in% unique(tissue_sc_info$donor)
  dset_df <- rbind(dset_df, data.frame("subj" = s, "bulk" = bulk, "single cell" = sc))
}
dset_df <- reshape2::melt(dset_df, id.vars = "subj")
tiles <- ggplot(dset_df, aes(x = variable, y = subj, fill = value)) +
  geom_tile(color = "black") +
  scale_fill_manual(values = c("white", "#5A5A5A")) +
  ylab("") + xlab("") +
  # geom_rect(mapping = aes(xmin = variable, max - )) +
  theme_minimal(base_size = 20) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")

myo_exp_tcrs <- lapply(blood_overlap_subjs, function(s){
  subj_tcrs <- c()
  # See if they have bulk TCR
  if(s %in% names(bulk_tissue_samples)){
    bulk_samp <- bulk_tissue_samples[[s]]$myo
    bulk_tcrs <- bulk_tcr_df[bulk_tcr_df$sample == bulk_samp,] %>%
      dplyr::select(amino_acid, count_templates_reads) %>%
      group_by(amino_acid) %>%
      summarise(n = sum(count_templates_reads)) %>%
      mutate(perc = n / sum(n) * 100)
    bulk_exp <- bulk_tcrs$amino_acid[bulk_tcrs$perc > 0.5 & bulk_tcrs$n > 1]
    subj_tcrs <- c(subj_tcrs, bulk_exp)
  }
  # See if they have single cell TCR
  if (s %in% unique(tissue_sc_info$donor)){
    subj_sc <- tissue_sc_info[tissue_sc_info$donor == s,] %>%
      dplyr::filter(TRB_cdr3 != "") %>%
      dplyr::select(TRB_cdr3) %>%
      mutate("count" =  1) %>%
      group_by(TRB_cdr3) %>%
      summarise(n = sum(count)) %>%
      mutate(perc = n / sum(n) * 100)
    sc_exp <- subj_sc$TRB_cdr3[subj_sc$perc > 0.5 & subj_sc$n > 1]
    subj_tcrs <- c(subj_tcrs, sc_exp)
  }
  return(unique(subj_tcrs))
})
names(myo_exp_tcrs) <- blood_overlap_subjs

n_exp_tcrs <- lapply(myo_exp_tcrs, function(x) length(x)) %>%
  as.data.frame() %>%
  t() %>%
  `colnames<-`(c("n")) %>%
  as.data.frame() %>%
  rownames_to_column(var = "subj")

exp_bars <- ggplot(n_exp_tcrs, aes(x = n, y = subj)) +
  geom_bar(stat = "identity") +
  # scale_x_log10() +
  # annotation_logticks(side = "b", outside = TRUE) +
  # coord_cartesian(clip = "off") +
  ylab("") +
  xlab("# expanded CDR3s") +
  theme_classic(base_size = 20)

# Plot with everything combined
ggarrange(plotlist = list(exp_bars, bars, tiles), nrow = 1, ncol = 3, widths = c(1,1, 0.3), align = "h")

```

## Supplemental figure 4C

```{r fig_S4C}

dset_df <- data.frame()
for (s in blood_overlap_subjs){
  if (!s %in% healing_ids){
    bulk <- s %in% names(bulk_tissue_samples)
  } else {
    bulk <- FALSE
  }
  sc <- s %in% unique(tissue_sc_info$donor)
  dset_df <- rbind(dset_df, data.frame("subj" = s, "bulk" = bulk, "single cell" = sc))
}

bulk_subjs <- dset_df[dset_df$bulk == TRUE,]$subj


bulk_exp_props <- lapply(bulk_subjs, function(s){
  bulk_samp <- bulk_tissue_samples[[s]]$myo
  bulk_tcrs <- bulk_tcr_df[bulk_tcr_df$sample == bulk_samp,] %>%
    dplyr::select(amino_acid, count_templates_reads) %>%
    group_by(amino_acid) %>%
    summarise(n = sum(count_templates_reads)) %>%
    mutate(perc = n / sum(n) * 100) %>%
    filter(perc > 0.5, n > 1) %>%
    mutate(donor = s,dtype = "bulk")
  colnames(bulk_tcrs)[colnames(bulk_tcrs) == "amino_acid"] <- "TRB_cdr3"
  return(bulk_tcrs)
}) %>%
  do.call(rbind, .)

sc_subjs <- dset_df[dset_df$single.cell == TRUE,]$subj

sc_exp_props <- lapply(sc_subjs, function(s){
  subj_sc <- tissue_sc_info[tissue_sc_info$donor == s,] %>%
    dplyr::filter(TRB_cdr3 != "") %>%
    dplyr::select(TRB_cdr3) %>%
    mutate("count" =  1) %>%
    group_by(TRB_cdr3) %>%
    summarise(n = sum(count)) %>%
    mutate(perc = n / sum(n) * 100) %>%
    filter(perc > 0.5, n > 1) %>%
    mutate(donor = s, dtype = "single cell")
  return(subj_sc)
}) %>%
  do.call(rbind, .)

plot_df <- rbind(bulk_exp_props, sc_exp_props)
order <- plot_df %>%
  arrange(desc(perc)) %>%
  .$TRB_cdr3 %>%
  unique()
plot_df$TRB_cdr3 <- factor(plot_df$TRB_cdr3, levels = order)
plot_df <- plot_df %>%
  arrange(perc)

ggplot(plot_df, aes(y = donor, x = perc, fill = perc)) +
  geom_bar(position = "stack", stat = "identity", color = "black") +
  facet_wrap(~dtype, scales = "free_y") +
  # scale_fill_continuous(type = "viridis") +
  scale_fill_distiller(palette = "YlOrRd", direction = 1) +
  ylab("") +
  xlab("% of repertoire") +
  theme_classic(base_size = 20) +
  theme(legend.position = "none")

```

## Supplemental figure 4D

```{r fig_S4D, message=FALSE, warning=FALSE, fig.height = 20, fig.width = 20}

fisher_res <- data.frame()
all_seq_info <- data.frame()

# Lets just look at subjects where we have control tissue
case_control_subjs <- c("SIC_3", "SIC_136", "SIC_17", "SIC_175")

for (subj in case_control_subjs){
  # Get the data for the subject
  subj_data <-  bulk_tcr_df %>%
    dplyr::filter(id == subj)

  subj_by_aa <- subj_data %>%
    dplyr::select(sample, tissue, amino_acid, count_templates_reads) %>%
    group_by(sample, tissue, amino_acid) %>%
    summarise("n_count_aa" = sum(count_templates_reads)) %>%
    group_by(sample) %>%
    dplyr::mutate("perc_of_samp" = n_count_aa / sum(n_count_aa)) # Lets get the proportion of each TCR AA seq in sample

  # Now make seperate dataframes
  subj_split <- split(subj_by_aa, f = subj_by_aa$sample)
  samp_info <- bulk_tissue_samples[[subj]]

  tumor_data <- subj_split[[samp_info$tumor]] %>%
    ungroup() %>%
    dplyr::select(amino_acid, perc_of_samp, n_count_aa) %>%
    `colnames<-`(c("amino_acid", "perc_tumor", "n_tumor"))

  control_data <- subj_split[[samp_info$control]] %>%
    ungroup %>%
    dplyr::select(amino_acid, perc_of_samp, n_count_aa) %>%
    `colnames<-`(c("amino_acid", "perc_control", "n_control"))

  myo_data <- subj_split[[samp_info$myo]] %>%
    ungroup %>%
    dplyr::select(amino_acid, perc_of_samp, n_count_aa) %>%
    `colnames<-`(c("amino_acid", "perc_myo", "n_myo"))

  info_df <- list(tumor_data, control_data, myo_data) %>%
    reduce(full_join, by = c("amino_acid"))
  info_df[is.na(info_df)] <- 0

  info_df$subj <- subj
  # Save all the seq info to a dataframe for a ranking plot
  all_seq_info <- rbind(all_seq_info, info_df)

  # Limit to TCRs found in at least tumor or myo, don't care about those exclusive to control
  info_df %<>%
    dplyr::filter(perc_tumor > 0.005 | perc_myo > 0.005) %>%
    dplyr::filter(n_control > 0) # Decided on this filter to be as strict as possible with analysis
  # Now that we have every TCR and its counts in the tumor, control, myo, lets do the stats
  stats_fisher <- lapply(info_df$amino_acid, function(seq){
    seq_info <- info_df %>% dplyr::filter(amino_acid == seq)
    d <- data.frame(group = c("ctrl", "myo", "tumor"),
                    tcr1_n = c(seq_info$n_control, seq_info$n_myo, seq_info$n_tumor),
                    tcr1_p = c(seq_info$perc_control, seq_info$perc_myo, seq_info$perc_tumor)) %>%
      dplyr::mutate(total_n = c(sum(control_data$n_control), sum(myo_data$n_myo), sum(tumor_data$n_tumor)))

    fisher_myo <- fisher.test(matrix(c(d$tcr1_n[d$group == "myo"],
                                       d$total_n[d$group == "myo"] - d$tcr1_n[d$group == "myo"],
                                       d$tcr1_n[d$group == "ctrl"],
                                       d$total_n[d$group == "ctrl"] - d$tcr1_n[d$group == "ctrl"]), nrow = 2))
    fisher_myo <- broom::tidy(fisher_myo) %>%
      `colnames<-`(paste("fisher", colnames(.), sep = "_")) %>%
      dplyr::mutate(term = "groupmyo")
    fisher_tumor <- fisher.test(matrix(c(d$tcr1_n[d$group == "tumor"],
                                       d$total_n[d$group == "tumor"] - d$tcr1_n[d$group == "tumor"],
                                       d$tcr1_n[d$group == "ctrl"],
                                       d$total_n[d$group == "ctrl"] - d$tcr1_n[d$group == "ctrl"]), nrow = 2))
    fisher_tumor <- broom::tidy(fisher_tumor) %>%
      `colnames<-`(paste("fisher", colnames(.), sep = "_")) %>%
      dplyr::mutate(term = "grouptumor")
    fish_res <- rbind(fisher_myo, fisher_tumor) %>%
      mutate(seq = seq)
    return(fish_res)
  }) %>%
    do.call(rbind, .) %>%
    mutate(subj = subj)

  fisher_by_seq <- data.frame()
  for(s in unique(stats_fisher$seq)){
  seq_info <- stats_fisher %>% dplyr::filter(seq == s)
  df <- data.frame(amino_acid = s,
                   subj = unique(seq_info$subj),
                   myo_log_fc = seq_info$fisher_estimate[seq_info$term == "groupmyo"],
                   tumor_log_fc = seq_info$fisher_estimate[seq_info$term == "grouptumor"],
                   myo_pval = seq_info$fisher_p.value[seq_info$term == "groupmyo"],
                   tumor_pval = seq_info$fisher_p.value[seq_info$term == "grouptumor"],
                   myo_estimate = seq_info$fisher_estimate[seq_info$term == "groupmyo"],
                   tumor_estimate = seq_info$fisher_estimate[seq_info$term == "grouptumor"])
  fisher_by_seq <- rbind(fisher_by_seq, df)
  }
  fisher_by_seq %<>%
    dplyr::left_join(info_df, by = c("amino_acid", "subj"))
  fisher_by_seq$tum_ctl_fc <- sapply(fisher_by_seq$amino_acid, function(s){

    # If it doesn't exist in either, fold-change is set to 1
    if (!s %in% tumor_data$amino_acid & !s %in% control_data$amino_acid){
      return(1)
    }

    # Adding pseudocunts to deal with zeros
    if (s %in% tumor_data$amino_acid){
      perc_tum <- (tumor_data$n_tumor[tumor_data$amino_acid == s] + 1) / (sum(tumor_data$n_tumor) + 1)
    } else {
      perc_tum <- 1 /  (sum(tumor_data$n_tumor) + 1)
    }

    if (s %in% control_data$amino_acid){
      perc_ctl <- (control_data$n_control[control_data$amino_acid == s] + 1) / (sum(control_data$n_control) + 1)
    } else {
      perc_ctl <- 1 / (sum(control_data$n_control) + 1)
    }
    return(perc_tum / perc_ctl)

  })
  fisher_by_seq$myo_ctl_fc <- sapply(fisher_by_seq$amino_acid, function(s){

    if (!s %in% myo_data$amino_acid & !s %in% control_data$amino_acid){
      return(1)
    }
    # Adding pseudocunts to deal with zeros
    if (s %in% myo_data$amino_acid){
      perc_myo <- (myo_data$n_myo[myo_data$amino_acid == s] + 1) / (sum(myo_data$n_myo) + 1)
    } else {
      perc_myo <- 1 /  (sum(myo_data$n_myo) + 1)
    }

    if (s %in% control_data$amino_acid){
      perc_ctl <- (control_data$n_control[control_data$amino_acid == s] + 1) / (sum(control_data$n_control) + 1)
    } else {
      perc_ctl <- 1 / (sum(control_data$n_control) + 1)
    }
    return(perc_myo / perc_ctl)

  })

  # fisher_by_seq$tum_ctl_fc <- fisher_by_seq$perc_tumor / fisher_by_seq$perc_control
  # fisher_by_seq$myo_ctl_fc <- fisher_by_seq$perc_myo / fisher_by_seq$perc_control
  # fisher_by_seq$myo_tum_fc <- fisher_by_seq$perc_myo / fisher_by_seq$perc_tumor

  fisher_res <- rbind(fisher_res, fisher_by_seq)

}

fisher_res$myo_padj <-p.adjust(fisher_res$myo_pval, method = "fdr")
fisher_res$tumor_padj <-p.adjust(fisher_res$tumor_pval, method = "fdr")


fisher_res$tum_ctl_fc[fisher_res$tum_ctl_fc > 50] <- 50
fisher_res$myo_ctl_fc[fisher_res$myo_ctl_fc > 50] <- 50

fisher_res$myo_enriched <- ifelse(fisher_res$myo_padj < 0.05 & fisher_res$myo_log_fc > 1, TRUE, FALSE)
fisher_res$tum_enriched <- ifelse(fisher_res$tumor_padj < 0.05 & fisher_res$tumor_log_fc > 1, TRUE, FALSE)
fisher_res$sig_cat <- ifelse(fisher_res$myo_enriched == TRUE,
                               ifelse(fisher_res$tum_enriched == TRUE, "enriched in both", "myo enriched"),
                               ifelse(fisher_res$tum_enriched == TRUE, "tumor enriched", "not enriched"))

fisher_res$sig_cat <- factor(fisher_res$sig_cat, levels = c("myo enriched", "tumor enriched", "enriched in both", "not enriched"))

order <- c("SIC_17", "SIC_136", "SIC_3", "SIC_175")
pheno_list <- c("SIC_17" = "Active", "SIC_136" = "Borderline", "SIC_3" = "Healing", "SIC_175" = "Healing")
plot_list <- list()
n_enriched_df <- data.frame()
for (subj in order){
  plot_df <- fisher_res[fisher_res$subj == subj,]
  pheno <- pheno_list[[subj]]
  if (subj == "SIC_175"){
      xlab = "Prop. tumor"
    } else {
      xlab = ""
    }

  plot_df$enriched <- plot_df$sig_cat
  count_df <- data.frame("subj" = subj,
             "n_tumor" = nrow(plot_df[plot_df$enriched == "tumor enriched",]),
             "n_myo" = nrow(plot_df[plot_df$enriched == "myo enriched",]),
             "n_both" = nrow(plot_df[plot_df$enriched == "enriched in both",]))

  n_enriched_df <- rbind(n_enriched_df, count_df)

  xlimit <- max(c(plot_df$perc_tumor, plot_df$perc_myo))
  # plot_df$enriched <- factor(plot_df$enriched, levels = c("myo enriched", "tumor enriched", "enriched in both", "not enriched"))
  ctl_tumor <- ggplot(plot_df, aes(x = perc_tumor, y = perc_control, fill = enriched, size = enriched)) +
      geom_point(data = plot_df[plot_df$enriched == "not enriched",], pch = 21) +
      geom_point(data = plot_df[plot_df$enriched != "not enriched",], pch = 21) +

      geom_abline(slope = 1, size = 2, linetype = "dashed") +
      scale_fill_manual(name = "",  values = c("myo enriched" = '#7CAE00', "tumor enriched" = '#C77CFF',
                                               "enriched in both" = '#F8766D', "not enriched" = "grey")) +
      scale_size_manual(guide = "none", values = c("myo enriched" = 5, "tumor enriched" = 5,
                                                   "enriched in both" = 5, "not enriched" = 3)) +
      scale_x_continuous(limits = c(0, xlimit)) +
      # xlab("prop. tumor") +
      xlab("Prop. tumor") +
      ylab("Prop. control") +
      ggtitle(glue("{subj} : {pheno}")) +
      theme_classic(base_size = 30) +
      guides(fill = guide_legend(override.aes = list(size=8))) +
    theme(plot.title = element_text(size=30, face = "bold"))

  myo_ctl <- ggplot(plot_df, aes(x = perc_myo, y = perc_control, fill = enriched, size = enriched)) +
       geom_point(data = plot_df[plot_df$enriched == "not enriched",], pch = 21) +
      geom_point(data = plot_df[plot_df$enriched != "not enriched",], pch = 21) +
      geom_abline(slope = 1, size = 2, linetype = "dashed") +
       scale_fill_manual(name = "", values = c("myo enriched" = '#7CAE00', "tumor enriched" = '#C77CFF',
                                               "enriched in both" = '#F8766D', "not enriched" = "grey")) +
      scale_size_manual(guide = "none", values = c("myo enriched" = 5, "tumor enriched" = 5,
                                                   "enriched in both" = 5, "not enriched" = 3)) +
      scale_x_continuous(limits = c(0, xlimit)) +
      xlab("Prop. myocarditis") +
      ylab("Prop. control") +
      theme_classic(base_size = 30) +
      guides(fill = guide_legend(override.aes = list(size=8)))

  myo_tum <- ggplot(plot_df, aes(x = perc_myo, y = perc_tumor, fill = enriched, size = enriched)) +
       geom_point(data = plot_df[plot_df$enriched == "not enriched",], pch = 21) +
      geom_point(data = plot_df[plot_df$enriched != "not enriched",], pch = 21) +
      geom_abline(slope = 1, size = 2, linetype = "dashed") +
       scale_fill_manual(name = "", values = c("myo enriched" = '#7CAE00', "tumor enriched" = '#C77CFF',
                                               "enriched in both" = '#F8766D', "not enriched" = "grey")) +
      scale_size_manual(guide = "none", values = c("myo enriched" = 5, "tumor enriched" = 5,
                                                   "enriched in both" = 5, "not enriched" = 3)) +
      scale_x_continuous(limits = c(0, xlimit)) +
      xlab("Prop. myocarditis") +
      ylab("Prop. tumor") +
      theme_classic(base_size = 30) +
      guides(fill = guide_legend(override.aes = list(size=8)))

  plot_list <- c(plot_list, list(ctl_tumor, myo_ctl, myo_tum))

}

figure <- ggarrange(plotlist = plot_list, ncol = 3, nrow = 4, common.legend = TRUE, legend = "top", align = "hv")
figure

```


## Supplemental figure 4E

```{r fig_S4E, warning=FALSE, message=FALSE, fig.width=12, fig.height=8}
plot_list = list()
for (subj in unique(fisher_res$subj)){
  print(subj)
  subj_plot <- fisher_res
  subj_plot$in_subj <- ifelse(subj_plot$subj == subj, "yes", "no")
  subj_plot$sig_cat <- as.character(subj_plot$sig_cat)
  subj_plot$sig_cat <- ifelse(subj_plot$in_subj == "yes", subj_plot$sig_cat, "no")
  subj_plot$sig_cat <- factor(subj_plot$sig_cat, levels = c("myo enriched", "tumor enriched", "enriched in both", "not enriched", "no"))

  p <- ggplot(subj_plot, aes(x = myo_ctl_fc, y = tum_ctl_fc)) +
    geom_point(data = subj_plot[subj_plot$sig_cat == "no",], pch = 21, size = 2) +
    geom_point(data = subj_plot[subj_plot$sig_cat != "no",], pch = 21, size = 4, aes(fill = sig_cat)) +
    scale_fill_manual(values = c("myo enriched" = "#7CAE00",
                                 "tumor enriched" = "#C77CFF",
                                 "enriched in both" = "#F8766D",
                                 "not enriched" = "grey")) +
    xlab("% Myocarditis : % control") +
    ylab("% Tumor : % control") +
    theme_classic(base_size = 20) +
    ggtitle(subj) +
    theme(legend.title = element_blank())

  if (subj == "SIC_136"){
    leg = get_legend(p)
  }

  plot_list <- c(plot_list, list(p))
}

ggarrange(plotlist = plot_list, common.legend = TRUE, legend.grob = leg, legend = "right")

```

## Supplemental figure 4G

```{r fig_s4g}

adaptive_to_imgt <- read.csv("/projects/home/nealpsmith/data/useful/adaptive_to_imgt_v_genes.csv")
adaptive_to_imgt_human <- adaptive_to_imgt[adaptive_to_imgt$species == "human",]
adaptive_to_imgt_v <- adaptive_to_imgt_human[grepl("TCRBV", adaptive_to_imgt_human$adaptive),] %>%
  `colnames<-`(c("adaptive", "imgt_v", "species"))
adaptive_to_imgt_j <- adaptive_to_imgt_human[grepl("TCRBJ", adaptive_to_imgt_human$adaptive),] %>%
    `colnames<-`(c("adaptive", "imgt_j", "species"))
productive_tcr_df <- read.csv("/projects/home/nealpsmith/projects/myocarditis/data/adaptive/all_productive_tcrs.csv", row.names = 1)
productive_tcr_df %<>%
  left_join(adaptive_to_imgt_v, by = c("v_gene_name" = "adaptive")) %>%
  left_join(adaptive_to_imgt_j, by = c("j_gene_name" = "adaptive"))

productive_tcr_df$simple_v_gene <- sapply(productive_tcr_df$imgt_v, function(x) strsplit(x, "*", fixed = TRUE)[[1]][1])
productive_tcr_df$simple_j_gene <- sapply(productive_tcr_df$imgt_j, function(x) strsplit(x, "*", fixed = TRUE)[[1]][1])

case_control_subjs <- c("SIC_3", "SIC_136", "SIC_17", "SIC_175")
motif_perc_df <- data.frame()
n_tcrs_in_groups <- data.frame()
gliph_list <- list()
for (subj in case_control_subjs){
  gliph_groups <- read.csv(glue("/projects/home/nealpsmith/projects/myocarditis/gliph/data/gliph_output/gliph_results_{subj}.csv"))

  group_split <- split(gliph_groups, gliph_groups$type)

  # Need to get the global ones
  # Global ones all the same length, "motif" only can have differing lengths
  names(group_split) <- sapply(names(group_split), function(x) gsub("motif.* ", "", x))

  gliph_keep <- sapply(group_split, function(x) length(unique(x$TcRb))) > 2

  gliph_filtered <- group_split[gliph_keep]
  gliph_list[[subj]] <- gliph_filtered
  n_tcr_count <- sapply(gliph_filtered, function(x) length(unique(x$TcRb))) %>% as.data.frame(row.names = names(.)) %>%
    `colnames<-`(c("n_unique_tcrs"))
  n_tcr_count$subj <- subj
  n_tcrs_in_groups <- rbind(n_tcrs_in_groups, n_tcr_count)

  # Calculate the prop of clones in all 3 compartments that have the motif
  myo_samp <- bulk_tissue_samples[[subj]]$myo
  control_samp <- bulk_tissue_samples[[subj]]$control
  tumor_samp <- bulk_tissue_samples[[subj]]$tumor

  subj_data <-  productive_tcr_df %>%
    dplyr::filter(id == subj)

  subj_by_aa <- subj_data %>%
    dplyr::select(sample, tissue, amino_acid, simple_v_gene, simple_j_gene, count_templates_reads) %>%
    group_by(sample, tissue, amino_acid, simple_v_gene, simple_j_gene) %>%
    summarise("n_count_aa" = sum(count_templates_reads)) %>%
    group_by(sample) %>%
    dplyr::mutate("perc_of_samp" = n_count_aa / sum(n_count_aa)) # Lets get the proportion of each TCR AA seq in sample
  myo_dat <- subj_by_aa %>%
      dplyr::filter(sample == myo_samp) %>%
      dplyr::filter(!is.na(simple_v_gene)) %>%
      dplyr::select(amino_acid, simple_v_gene, simple_j_gene, n_count_aa,perc_of_samp)

  tumor_dat <- subj_by_aa %>%
    dplyr::filter(sample == tumor_samp) %>%
    dplyr::filter(!is.na(simple_v_gene)) %>%
    dplyr::select(amino_acid, simple_v_gene, simple_j_gene, n_count_aa, perc_of_samp)

  control_dat <- subj_by_aa %>%
    dplyr::filter(sample == control_samp) %>%
    dplyr::filter(!is.na(simple_v_gene)) %>%
    dplyr::select(amino_acid, simple_v_gene, simple_j_gene, n_count_aa, perc_of_samp)

  # Iterate through the motifs
  percs <- lapply(names(gliph_filtered), function(gg){
    gg_dat <- gliph_filtered[[gg]]
    tcrs <- unique(gg_dat$TcRb)
    myo_perc <- myo_dat %>%
      dplyr::filter(amino_acid %in% tcrs) %>%
      .$perc_of_samp %>%
      sum() * 100
    tumor_perc <- tumor_dat %>%
      dplyr::filter(amino_acid %in% tcrs) %>%
      .$perc_of_samp %>%
      sum() * 100
    control_perc <- control_dat %>%
      dplyr::filter(amino_acid %in% tcrs) %>%
      .$perc_of_samp %>%
      sum() * 100
    df <- data.frame("myo_perc" = myo_perc,
                     "tumor_perc" = tumor_perc,
                     "control_perc" = control_perc,
                     "motif" = gg)
  }) %>%
      do.call(rbind, .)
  percs$subj <- subj

  motif_perc_df <- rbind(motif_perc_df, percs)
}

fisher_res$in_gliph <- apply(fisher_res, 1, function(df){
  subj <- df[["subj"]]
  seq <- df[["amino_acid"]]
  gliph_groups <- read.csv(glue("/projects/home/nealpsmith/projects/myocarditis/gliph/data/gliph_output/gliph_results_{subj}.csv"))
  group_split <- split(gliph_groups, gliph_groups$type)

  # Need to get the global ones
  # Global ones all the same length, "motif" only can have differing lengths
  names(group_split) <- sapply(names(group_split), function(x) gsub("motif.* ", "", x))

  gliph_keep <- sapply(group_split, function(x) length(unique(x$TcRb))) > 2

  gliph_filtered <- group_split[gliph_keep]

  gliph_tcrs <- lapply(gliph_filtered, function(x) x$TcRb) %>%
    unlist(., use.names = FALSE)
  in_gliph <- seq %in% gliph_tcrs
  return(in_gliph)
})

ggplot(fisher_res, aes(x = myo_ctl_fc, y = tum_ctl_fc)) +
  geom_point(data = fisher_res %>% dplyr::filter(in_gliph == FALSE), pch = 21, size = 3, aes(fill = "grey")) +
  geom_point(data = fisher_res %>% dplyr::filter(in_gliph == TRUE), pch = 21, size = 4, aes(fill = "red")) +
  scale_fill_manual(values = c("grey", "red"), labels = c("False", "True"), name = "in GLIPH group") +
  xlab("% Myocarditis : % control") +
  ylab("% Tumor : % control") +
  ggtitle("Expanded TCRs (figure 3B)") +
  theme_classic(base_size = 20)
```


```{r fig_s4h}

motif_perc_df$myo_to_ctrl <- motif_perc_df$myo_perc / motif_perc_df$control_perc
motif_perc_df$tum_to_ctrl <- motif_perc_df$tumor_perc / motif_perc_df$control_perc

motif_perc_df$myo_to_ctrl[motif_perc_df$myo_to_ctrl == "Inf"] <- 90
motif_perc_df$tum_to_ctrl[motif_perc_df$tum_to_ctrl == "Inf"] <- 90

motif_perc_df[is.na(motif_perc_df)] <- 0

plot_df <- motif_perc_df %>%
  dplyr::filter(myo_perc > 0.5 | tumor_perc > 0.5)

plot_df$motif_clean <- sapply(plot_df$motif, function(x) strsplit(x, "-")[[1]][2])
ggplot(plot_df, aes(x = myo_to_ctrl, y = tum_to_ctrl, fill = subj)) +
  geom_point(pch = 21, size= 3,
             # position = position_jitterdodge(jitter.width = 1, jitter.height = 1)
  ) +
  xlab("% myocarditis : % control") +
  ylab("% tumor : % control") +
  ggtitle("GLIPH groups") +
  geom_label_repel(data = plot_df %>% dplyr::filter(myo_to_ctrl > 10 | tum_to_ctrl > 10), aes(label = motif_clean), show.legend = FALSE) +
  theme_classic(base_size = 20)

```