---
title: "Supplemental Figure 7"
output: rmarkdown::github_document
---


## Setup

Load R libraries
```{r message=FALSE}
library(tidyverse)
library(glue)
library(rlang)
library(parameters)
library(ggforestplot)
library(rmarkdown)
library(knitr)

library(reticulate)
use_python("/projects/home/nealpsmith/.conda/envs/updated_pegasus/bin/python")

setwd('/projects/home/nealpsmith/publication_githubs/myocarditis/functions')
source('stacked_bar.R')
source('blood_condition_abundance.R')
```


Load Python packages
```{python load_python_packages}
import pegasus as pg
import scanpy as sc
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append("/projects/home/nealpsmith/publication_githubs/myocarditis/functions")
import python_functions
```


Read in single-cell data
```{python results = 'hide', read_data}
tissue_mnp = pg.read_input('/projects/home/ikernin/projects/myocarditis/github_datasets/tissue_myeloid.zarr')
```


## Supplemental Figure 7A

```{python supp_7A}

supp_7a_genes = ["LILRB1", "LILRB2", "FLT3", "CD1C", "CLEC9A", "GPNMB", "FABP5", "FCN1", "CX3CR1"]
python_functions.multi_hex_featureplot(tissue_mnp,
                      supp_7a_genes,
                      ncol=4,
                      cmap=python_functions.blues_cmap,
                      gridsize=200)

```

## Supplemental Figure 7B

```{python supp_7b}
tissue_mnp.obs['Condition'] = [x.capitalize() for x in tissue_mnp.obs['condition']]
tissue_mnp = tissue_mnp.to_anndata()
sc.tl.embedding_density(tissue_mnp, groupby='Condition')
sc.pl.embedding_density(tissue_mnp, basis='umap', key=f'umap_density_Condition')
```


## Supplemental Figure 7C

```{python supp_7c_get_data}
tissue_mnp = pg.read_input('/projects/home/ikernin/projects/myocarditis/github_datasets/tissue_myeloid.zarr')

stacked_bar_df = python_functions.get_stacked_bar_df(tissue_mnp, 'mnp')
stacked_bar_order = tissue_mnp.obs['umap_name'].cat.categories.values
```

```{r supp_7c_plot}
stacked_bar_order = py$stacked_bar_order[!str_detect(py$stacked_bar_order, 'Doublets')]
plot_clust_perc_by_donor(py$stacked_bar_df, 'mnp', cluster_order = stacked_bar_order)
```


```{r message = F, warning = F, results = 'hold',  fig.width = 15, fig.height = 10, fig_5c}
# read in tissue data
tissue_obs <- read_csv('/projects/home/ikernin/projects/myocarditis/updated_datasets/metadata/tissue_full_obs.csv')

# filter
masc_df <- masc_filter(tissue_obs)

# read in masc res (from figure 3 code)
cluster_masc_res <- read_csv('/projects/home/ikernin/projects/myocarditis/updated_datasets/masc/cluster_masc_res.csv')

# plot masc results
plot_masc_by_cell_type(cluster_masc_res, masc_df, lineage='MNP')
```