---
title: "Supplemental Figure 6"
output: rmarkdown::github_document
---


## Setup

Load R libraries
```{r message=FALSE}
library(tidyverse)
library(glue)
library(rlang)
library(parameters)
library(ggforestplot)
library(rmarkdown)
library(knitr)

library(reticulate)
use_python("/projects/home/nealpsmith/.conda/envs/updated_pegasus/bin/python")

setwd('/projects/home/ikernin/github_code/myocarditis/functions')
source('stacked_bar.R')
source('blood_condition_abundance.R')
```


Load Python packages
```{python load_python_packages}
import pegasus as pg
import scanpy as sc
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append("/projects/home/ikernin/github_code/myocarditis/functions")
import python_functions
```


Read in single-cell data
```{python results = 'hide', read_data}
tissue_mnp = pg.read_input('/projects/home/ikernin/projects/myocarditis/github_datasets/tissue_myeloid.zarr')
blood_mnp = pg.read_input('/projects/home/ikernin/projects/myocarditis/github_datasets/blood_myeloid.zarr')
```


## Supplemental Figure 6A

```{python supp_6a}
tissue_mnp.obs['Condition'] = [x.capitalize() for x in tissue_mnp.obs['condition']]
tissue_mnp = tissue_mnp.to_anndata()
sc.tl.embedding_density(tissue_mnp, groupby='Condition')
sc.pl.embedding_density(tissue_mnp, basis='umap', key=f'umap_density_Condition', colorbar_loc=None)
```


## Supplemental Figure 6B

```{python supp_6b_get_data}
stacked_bar_df = python_functions.get_stacked_bar_df(tissue_mnp, 'mnp')
stacked_bar_order = tissue_mnp.obs['umap_name'].cat.categories.values
```

```{r supp_6b_plot}
stacked_bar_order = py$stacked_bar_order[!str_detect(py$stacked_bar_order, 'Doublets')]
plot_clust_perc_by_donor(py$stacked_bar_df, 'mnp', cluster_order = stacked_bar_order)
```


## Supplemental Figure 6E

```{python supp_6e}
supp_fig6e_genes = ['CD14','IL1B','CD1C','FCGR3A','S100A12','LILRA4']
python_functions.multi_hex_featureplot(blood_mnp, supp_fig6e_genes, ncol=3, cmap=python_functions.blues_cmap, gridsize=200)
```


## Supplemental Figure 6F

```{python supp_6f}
python_functions.hex_plot(blood_mnp, "% Mito", n_genes=False, cmap=python_functions.blues_cmap)
python_functions.hex_plot(blood_mnp, "# Genes", n_genes=True, cmap=python_functions.blues_cmap)
```


## Supplemental Figure 6G

```{r message=FALSE, results='hold', supp_6g}
# read in all blood cell metadata
blood_global_obs <- read_csv('/projects/home/ikernin/projects/myocarditis/github_datasets/blood_global_obs.csv')
blood_obs_filtered <- condition_filter_df(blood_global_obs)

# fit cluster level model
cluster_percents <- condition_get_percent_per_level(blood_obs_filtered, level='cluster')
cluster_model <- condition_fit_model(cluster_percents, level='cluster')
cluster_lineages <- blood_obs_filtered %>% select(cluster_names, lineage_names) %>% distinct()

# get get myeloid lineage level results
myeloid_order <- c('b-MNP: S100A12 RETN', 'b-MNP: CD14 MARCKS', 'b-MNP: LGALS2 STAT1-low',
                   'b-MNP: IFI44L STAT1', 'b-MNP: Low-genes', 'b-MNP: FCGR3A CDKN1C',
                   'b-MNP: IL1R2 CD163', 'b-MNP: C1QC NR1H3', 'b-MNP: MT-high',
                   'b-MNP: CCL3 IL1B',"b-cDC: CD1C CLEC10A", "b-pDC: LILRA4 IRF8")
myeloid_percents <- cluster_percents %>% filter(cluster_names %in% myeloid_order)
myeloid_percents <- set_factor_order(myeloid_percents , col_name = 'cluster_names', order = myeloid_order)
myeloid_model <- cluster_model %>% filter(cluster_names %in% myeloid_order)
myeloid_model <- set_factor_order(myeloid_model , col_name = 'cluster_names', order = myeloid_order)
kable(myeloid_model %>%
              select(!c(data, model)) %>%
              unnest(cols = c(condition_coef, condition_se, condition_pval)))

condition_plot_sample_perc(myeloid_percents, title='Myeloid')
condition_plot_ci_interval(myeloid_model, 'Myeloid', level='cluster')
```