---
title: "Supplemental Figure 10"
output: html_document
---

## Set up

Load R libraries
```{r message=FALSE, load_r_libraries}
# load packages
library(tidyverse)
library(ggpubr)
library(ggplot2)
library(grid)
library(alakazam)
library(magrittr)
library(RColorBrewer)
library(reticulate)
use_python("/projects/home/nealpsmith/.conda/envs/updated_pegasus/bin/python")

setwd('/projects/home/ikernin/github_code/myocarditis/functions')
source('masc.R')
source('plot_masc.R')
source('de.R')
source('stacked_bar.R')

```


Load Python packages
```{python load_python_packages}
import pegasus as pg
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.sparse import csr_matrix
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append("/projects/home/ikernin/github_code/myocarditis/functions")
import python_functions
import scanpy as sc

```

## Supplemental figure 10C

```{r fig_s10c, warning = FALSE, fig.height = 10, fig.width = 10}

all_data <- read.csv("/projects/home/nealpsmith/projects/myocarditis/data/supplemental_tables/all_degs_concatenated.csv")
tcell_no_mm <- read.csv("/projects/home/nealpsmith/projects/myocarditis/data/t_no_micromets_de_by_condition_all_results.csv")
tcell_no_mm$X <- NULL
tcell_no_mm$cluster <- NULL
colnames(tcell_no_mm) <- c(paste("no_mm", colnames(tcell_no_mm)[1:6], sep = "_"), "gene_symbol", "cluster")


### MNP ###
mnp_no_mm <- read.csv("/projects/home/nealpsmith/projects/myocarditis/data/myeloid_no_micromets_de_by_condition_all_results.csv")
mnp_no_mm$X <- NULL
mnp_no_mm$cluster <- NULL
colnames(mnp_no_mm) <- c(paste("no_mm", colnames(mnp_no_mm)[1:6], sep = "_"), "gene_symbol", "cluster")

### Non-immune ###
nonimmune_no_mm <- read.csv("/projects/home/nealpsmith/projects/myocarditis/data/nonimmune_no_micromets_de_by_condition_all_results.csv")
nonimmune_no_mm$X <- NULL
nonimmune_no_mm$cluster <- NULL
colnames(nonimmune_no_mm) <- c(paste("no_mm", colnames(nonimmune_no_mm)[1:6], sep = "_"), "gene_symbol", "cluster")

### How about one for all DEGs ###
no_mm_data_all <- rbind(tcell_no_mm, mnp_no_mm, nonimmune_no_mm)

plot_degs_all <- all_data %>%
  dplyr::filter(tissue == "heart", padj < 0.1) %>%
  dplyr::left_join(no_mm_data_all, by = c("gene_symbol", "cluster"))

ggplot(plot_degs_all, aes(x = log2FoldChange, y = no_mm_log2FoldChange)) +
  # geom_point(data = plot_degs_all %>% dplyr::filter(label == ""), color = "grey") +
  geom_point(data = plot_degs_all, fill = "black", pch = 21, size = 3) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_abline() +
  ylab("log2FC : without cardiac metastases") +
  xlab("log2FC : with cardiac metastases") +
  # geom_text_repel(aes(label = label), min.segment.length = 0.1, max.overlaps = 100) +
  theme_classic(base_size = 20)

```


```{r fig_s10d}

bulk_tcr_df <- read.csv("/projects/home/nealpsmith/projects/myocarditis/data/adaptive/all_productive_tcrs.csv", row.names = 1)

bulk_tissue_samples = list("SIC_3" = list("tumor" = "A17-341_A2", "control" = "A17-341_A3", "myo" = "A17-341_A27"),
                           "SIC_232" = list("tumor" = "A19-395_A8", "control" = "A19-395_A7", "myo" = "A19-395_A53-1"),
                           "SIC_136" = list("tumor" = "A19-41_A10_Tumor", "control" = "A19-41_A10_Liver", "myo" = "A19-41_A33"),
                           "SIC_17" = list("tumor" = "A18-122_A51", "control" = "A18-122_A52", "myo" = "A18-122_A41"),
                           "SIC_175" = list("tumor" = "A19-230_A5", "control" = "T03054-11", "myo" = "A19-230_A48"),
                           "SIC_266" = list("myo" = "A20-363_A18"),
                           "SIC_264" = list("myo" = "A20-331_A1"),
                           # These are controls
                           "SIC_176" = list("myo" = "A19-213_A13"),
                           "SIC_14" = list("myo" = "T01708-11"),
                           # "SIC_182" = list("myo" = "A19-240_A15"),
                           "T01241" = list("myo" = "A16-303_A5")
)

control_ids <- c("SIC_176", "SIC_14", "T01241")
healing_ids <- c("SIC_3", "SIC_175", "SIC_266")
active <- c("SIC_264", "SIC_17")
micromets <- c("SIC_232", "SIC_136")

meta_df <- data.frame("category" = c("control", "control", "control",
                                     "healing", "healing", "healing",
                                     "active", "active", "cardiac mets", "cardiac mets"),
                      "id" = c("SIC_176", "SIC_14", "T01241",
                               "SIC_3", "SIC_175", "SIC_266", "SIC_264", "SIC_17", "SIC_136", "SIC_232"))


heart_tcrs <- lapply(names(bulk_tissue_samples), function(s){
  heart_samp <- bulk_tissue_samples[[s]][["myo"]]
  subj_tcrs <- bulk_tcr_df %>%
    dplyr::filter(sample == heart_samp) %>%
    dplyr::select(amino_acid, sample, id, count_templates_reads)
  return(subj_tcrs)
}) %>% do.call(rbind, .)



colnames(heart_tcrs)[colnames(heart_tcrs) == "amino_acid"] <- "clone_id"
# Only look at subjects with at least 200 TCRs
div_df <- heart_tcrs[,c("clone_id", "id", "count_templates_reads")]
# div_df <- div_df[div_df$id != "SIC_232",]

div <- alphaDiversity(div_df, group = "id", nboot = 100, min_n = 100, copy = "count_templates_reads")
div %<>%
  dplyr::left_join(meta_df, by = "id")


ggplot(div, aes_string(x = "q", y = "d", group = "id", color = "category")) +
  geom_line(size = 1) +
  # facet_wrap(~subj) +
  # scale_color_manual(values = c("blue", "red")) +
  ggtitle("Hill diversity index") + baseTheme() +
  xlab("q") + ylab("d") +
  theme_classic(base_size = 20) +
  theme(legend.title = element_blank())

```
